# NOTE: Using redis in development and testing, so that the scenario of two
#       browser windows can be demonstrated and tested.
default: &default
  adapter: redis
  url: redis://localhost:6379
development: *default
production: *default
test: *default
