# NOTE: This (as well as other "secrets") are commited to the repo since it's
# a demo app, not present in production. Having secrets in the repository makes
# it easier to get it running by someone pulling it for the first time.

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password:

development:
  <<: *defaults
  database: user_feed_app_development

test:
  <<: *defaults
  database: user_feed_app_test

production:
  <<: *defaults
  database: user_feed_app_production
